services:
  nginx:
    image: 192.168.202.85:5000/nginx:1.27
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /devops/nginx/html:/var/www/html:ro
      - /devops/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - /devops/nginx/conf.d:/etc/nginx/conf.d
      - /devops/nginx/logs:/var/log/nginx
    restart: always







