services:
  cadvisor:
    image: 192.168.202.85:5000/monitoring/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "8080:8080"
    restart: unless-stopped


  node-exporter:
    image: 192.168.202.85:5000/monitoring/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"


  portainer:
    image: 192.168.202.85:5000/monitoring/portainer-agent:latest
    container_name: portainer_agent
    restart: unless-stopped
    environment:
      - AGENT_CLUSTER_ADDR=tasks.portainer_agent
      - AGENT_PORT=9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"


{
  "insecure-registries": ["192.168.202.85:5000"]
}



nano /etc/docker/daemon.json
