services:
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - portainer-net

networks:
  portainer-net:
