
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=123
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - /devops/oracle/oradata:/opt/oracle/oradata
    restart: unless-stopped




